package config

const (
	// DefaultEnvPrefix is the canonical environment variable prefix.
	DefaultEnvPrefix = "AUREN"
)

var defaultSearchPaths = []string{
	".",
	"./configs",
	"/etc/auren-transfer-agent",
}

// DefaultSearchPaths returns the canonical config discovery locations.
func DefaultSearchPaths() []string {
	paths := make([]string, len(defaultSearchPaths))
	copy(paths, defaultSearchPaths)
	return paths
}

// DefaultConfig returns the official built-in configuration baseline.
func DefaultConfig() Config {
	return Config{
		App: AppConfig{
			Name:        "auren-transfer-agent",
			Description: "High-reliability media transfer agent",
		},
		Runtime: RuntimeConfig{
			Environment: "local",
			DataDir:     "./data",
			TempDir:     "./tmp",
		},
		Logger: LoggerConfig{
			Level:     "info",
			Format:    "json",
			Timestamp: true,
			Service:   "auren-transfer-agent",
		},
		Server: ServerConfig{
			Enabled:      false,
			Host:         "0.0.0.0",
			Port:         8080,
			ReadTimeout:  "30s",
			WriteTimeout: "30s",
			IdleTimeout:  "60s",
		},
		Worker: WorkerConfig{
			Enabled:         false,
			Concurrency:     1,
			ShutdownTimeout: "30s",
		},
		Queue: QueueConfig{
			Driver:             "memory",
			MemoryCapacity:     100,
			PollInterval:       "1s",
			RedisAddress:       "redis://localhost:6379",
			RedisStream:        "auren.transfer.jobs",
			RedisConsumerGroup: "auren-transfer-agents",
			RabbitMQURL:        "amqp://guest:guest@localhost:5672/",
			RabbitMQQueue:      "auren.transfer.jobs",
			NATSURL:            "nats://localhost:4222",
			NATSSubject:        "auren.transfer.jobs",
			NATSQueueGroup:     "auren-transfer-agents",
		},
		Resolver: ResolverConfig{
			DefaultUserAgent: "AurenTransferAgent/1.0",
			FollowRedirects:  true,
			MaxRedirects:     10,
		},
		Download: DownloadConfig{
			TempDir:               "./tmp/downloads",
			ConnectTimeout:        "15s",
			ResponseHeaderTimeout: "30s",
			IdleTimeout:           "60s",
			MaxRetries:            3,
			RetryBackoff:          "2s",
			ChunkSize:             "8MiB",
			ResumeEnabled:         true,
			Checksum:              "sha256",
		},
		Upload: UploadConfig{
			Driver:           "local",
			MaxRetries:       3,
			RetryBackoff:     "2s",
			MultipartEnabled: true,
			PartSize:         "16MiB",
		},
		Storage: StorageConfig{
			Driver:       "local",
			Endpoint:     "",
			Bucket:       "",
			APIKey:       "",
			Region:       "us-east-1",
			LocalPath:    "./data/storage",
			UsePathStyle: true,
		},
		Metrics: MetricsConfig{
			Enabled: false,
			Host:    "0.0.0.0",
			Port:    9090,
			Path:    "/metrics",
		},
		Heartbeat: HeartbeatConfig{
			Enabled:  false,
			Interval: "30s",
			Timeout:  "10s",
		},
		Security: SecurityConfig{
			APIKeyRequired:    false,
			APIKey:            "",
			APIKeyHash:        "",
			TokenHeader:       "Authorization",
			AllowInsecureHTTP: true,
			JWTEnabled:        false,
			JWTSecret:         "",
			JWTTTL:            "15m",
			MTLSEnabled:       false,
			MTLSRequiredCN:    "",
			RBACEnabled:       false,
			RateLimitEnabled:  false,
			RateLimitPerMin:   60,
			SecretsProvider:   "env",
			SecretsFile:       "",
		},
		MediaHub: MediaHubConfig{
			Enabled:                  false,
			BaseURL:                  "",
			RegistrationToken:        "",
			NodeUUID:                 "",
			NodeSecret:               "",
			HMACEnabled:              true,
			PollEnabled:              false,
			PollInterval:             "2s",
			TransferEnabled:          false,
			ClaimEnabled:             false,
			ClaimInterval:            "2s",
			ProgressInterval:         "5s",
			ControlInterval:          "10s",
			MaxConcurrentJobs:        1,
			AcceptedOperations:       "media_remote_download,playlist_m3u_download,remote_download",
			WorkDir:                  "./data/transfer",
			MinBytes:                 65536,
			BlockHTML:                true,
			GatewayEnabled:           false,
			GatewayProxyEnabled:      true,
			GatewayRedirectEnabled:   true,
			GatewayHeartbeatInterval: "10s",
			GatewayTokenTTL:          "5m",
			DrainEnabled:             true,
			DrainFile:                "./data/transfer/drain",
			BackpressureEnabled:      true,
			DiskGuardEnabled:         true,
			DiskMinFreeBytes:         1073741824,
			DeadLetterEnabled:        true,
			DeadLetterDir:            "./data/transfer/dead-letter",
			LeaseRenewalEnabled:      true,
			LeaseRenewalInterval:     "30s",
			SecretRotationEnabled:    false,
			SecretRotationInterval:   "24h",
			HeartbeatInterval:        "30s",
			MetricsInterval:          "60s",
			EventsFlushInterval:      "10s",
			Role:                     "gateway",
			Provider:                 "auren_transfer_agent",
			Region:                   "sa-east-1",
			AvailabilityZone:         "",
			PublicBaseURL:            "",
			HealthURL:                "",
			MaxSessions:              500,
			MaxEgressMbps:            1000,
			Capabilities:             "transfer,gateway,download,upload,auren_storage,xtream,shui,m3u8,hls,live,movie,series",
		},
	}
}

// DefaultValues returns the built-in defaults as dotted keys for Viper.
func DefaultValues() map[string]any {
	cfg := DefaultConfig()

	return map[string]any{
		"app.name":        cfg.App.Name,
		"app.description": cfg.App.Description,

		"runtime.environment": cfg.Runtime.Environment,
		"runtime.data_dir":    cfg.Runtime.DataDir,
		"runtime.temp_dir":    cfg.Runtime.TempDir,

		"logger.level":     cfg.Logger.Level,
		"logger.format":    cfg.Logger.Format,
		"logger.timestamp": cfg.Logger.Timestamp,
		"logger.service":   cfg.Logger.Service,

		"server.enabled":       cfg.Server.Enabled,
		"server.host":          cfg.Server.Host,
		"server.port":          cfg.Server.Port,
		"server.read_timeout":  cfg.Server.ReadTimeout,
		"server.write_timeout": cfg.Server.WriteTimeout,
		"server.idle_timeout":  cfg.Server.IdleTimeout,

		"worker.enabled":          cfg.Worker.Enabled,
		"worker.concurrency":      cfg.Worker.Concurrency,
		"worker.shutdown_timeout": cfg.Worker.ShutdownTimeout,

		"queue.driver":               cfg.Queue.Driver,
		"queue.memory_capacity":      cfg.Queue.MemoryCapacity,
		"queue.poll_interval":        cfg.Queue.PollInterval,
		"queue.redis_address":        cfg.Queue.RedisAddress,
		"queue.redis_stream":         cfg.Queue.RedisStream,
		"queue.redis_consumer_group": cfg.Queue.RedisConsumerGroup,
		"queue.rabbitmq_url":         cfg.Queue.RabbitMQURL,
		"queue.rabbitmq_queue":       cfg.Queue.RabbitMQQueue,
		"queue.nats_url":             cfg.Queue.NATSURL,
		"queue.nats_subject":         cfg.Queue.NATSSubject,
		"queue.nats_queue_group":     cfg.Queue.NATSQueueGroup,

		"resolver.default_user_agent": cfg.Resolver.DefaultUserAgent,
		"resolver.follow_redirects":   cfg.Resolver.FollowRedirects,
		"resolver.max_redirects":      cfg.Resolver.MaxRedirects,

		"download.temp_dir":                cfg.Download.TempDir,
		"download.connect_timeout":         cfg.Download.ConnectTimeout,
		"download.response_header_timeout": cfg.Download.ResponseHeaderTimeout,
		"download.idle_timeout":            cfg.Download.IdleTimeout,
		"download.max_retries":             cfg.Download.MaxRetries,
		"download.retry_backoff":           cfg.Download.RetryBackoff,
		"download.chunk_size":              cfg.Download.ChunkSize,
		"download.resume_enabled":          cfg.Download.ResumeEnabled,
		"download.checksum":                cfg.Download.Checksum,

		"upload.driver":            cfg.Upload.Driver,
		"upload.max_retries":       cfg.Upload.MaxRetries,
		"upload.retry_backoff":     cfg.Upload.RetryBackoff,
		"upload.multipart_enabled": cfg.Upload.MultipartEnabled,
		"upload.part_size":         cfg.Upload.PartSize,

		"storage.driver":         cfg.Storage.Driver,
		"storage.endpoint":       cfg.Storage.Endpoint,
		"storage.bucket":         cfg.Storage.Bucket,
		"storage.api_key":        cfg.Storage.APIKey,
		"storage.region":         cfg.Storage.Region,
		"storage.local_path":     cfg.Storage.LocalPath,
		"storage.use_path_style": cfg.Storage.UsePathStyle,

		"metrics.enabled": cfg.Metrics.Enabled,
		"metrics.host":    cfg.Metrics.Host,
		"metrics.port":    cfg.Metrics.Port,
		"metrics.path":    cfg.Metrics.Path,

		"heartbeat.enabled":  cfg.Heartbeat.Enabled,
		"heartbeat.interval": cfg.Heartbeat.Interval,
		"heartbeat.timeout":  cfg.Heartbeat.Timeout,

		"security.api_key_required":      cfg.Security.APIKeyRequired,
		"security.api_key":               cfg.Security.APIKey,
		"security.api_key_hash":          cfg.Security.APIKeyHash,
		"security.token_header":          cfg.Security.TokenHeader,
		"security.allow_insecure_http":   cfg.Security.AllowInsecureHTTP,
		"security.jwt_enabled":           cfg.Security.JWTEnabled,
		"security.jwt_secret":            cfg.Security.JWTSecret,
		"security.jwt_ttl":               cfg.Security.JWTTTL,
		"security.mtls_enabled":          cfg.Security.MTLSEnabled,
		"security.mtls_required_cn":      cfg.Security.MTLSRequiredCN,
		"security.rbac_enabled":          cfg.Security.RBACEnabled,
		"security.rate_limit_enabled":    cfg.Security.RateLimitEnabled,
		"security.rate_limit_per_minute": cfg.Security.RateLimitPerMin,
		"security.secrets_provider":      cfg.Security.SecretsProvider,
		"security.secrets_file":          cfg.Security.SecretsFile,

		"media_hub.enabled":                    cfg.MediaHub.Enabled,
		"media_hub.base_url":                   cfg.MediaHub.BaseURL,
		"media_hub.registration_token":         cfg.MediaHub.RegistrationToken,
		"media_hub.node_uuid":                  cfg.MediaHub.NodeUUID,
		"media_hub.node_secret":                cfg.MediaHub.NodeSecret,
		"media_hub.hmac_enabled":               cfg.MediaHub.HMACEnabled,
		"media_hub.poll_enabled":               cfg.MediaHub.PollEnabled,
		"media_hub.poll_interval":              cfg.MediaHub.PollInterval,
		"media_hub.transfer_enabled":           cfg.MediaHub.TransferEnabled,
		"media_hub.claim_enabled":              cfg.MediaHub.ClaimEnabled,
		"media_hub.claim_interval":             cfg.MediaHub.ClaimInterval,
		"media_hub.progress_interval":          cfg.MediaHub.ProgressInterval,
		"media_hub.control_interval":           cfg.MediaHub.ControlInterval,
		"media_hub.max_concurrent_jobs":        cfg.MediaHub.MaxConcurrentJobs,
		"media_hub.accepted_operations":        cfg.MediaHub.AcceptedOperations,
		"media_hub.work_dir":                   cfg.MediaHub.WorkDir,
		"media_hub.min_bytes":                  cfg.MediaHub.MinBytes,
		"media_hub.block_html":                 cfg.MediaHub.BlockHTML,
		"media_hub.gateway_enabled":            cfg.MediaHub.GatewayEnabled,
		"media_hub.gateway_proxy_enabled":      cfg.MediaHub.GatewayProxyEnabled,
		"media_hub.gateway_redirect_enabled":   cfg.MediaHub.GatewayRedirectEnabled,
		"media_hub.gateway_heartbeat_interval": cfg.MediaHub.GatewayHeartbeatInterval,
		"media_hub.gateway_token_ttl":          cfg.MediaHub.GatewayTokenTTL,
		"media_hub.drain_enabled":              cfg.MediaHub.DrainEnabled,
		"media_hub.drain_file":                 cfg.MediaHub.DrainFile,
		"media_hub.backpressure_enabled":       cfg.MediaHub.BackpressureEnabled,
		"media_hub.disk_guard_enabled":         cfg.MediaHub.DiskGuardEnabled,
		"media_hub.disk_min_free_bytes":        cfg.MediaHub.DiskMinFreeBytes,
		"media_hub.dead_letter_enabled":        cfg.MediaHub.DeadLetterEnabled,
		"media_hub.dead_letter_dir":            cfg.MediaHub.DeadLetterDir,
		"media_hub.lease_renewal_enabled":      cfg.MediaHub.LeaseRenewalEnabled,
		"media_hub.lease_renewal_interval":     cfg.MediaHub.LeaseRenewalInterval,
		"media_hub.secret_rotation_enabled":    cfg.MediaHub.SecretRotationEnabled,
		"media_hub.secret_rotation_interval":   cfg.MediaHub.SecretRotationInterval,
		"media_hub.heartbeat_interval":         cfg.MediaHub.HeartbeatInterval,
		"media_hub.metrics_interval":           cfg.MediaHub.MetricsInterval,
		"media_hub.events_flush_interval":      cfg.MediaHub.EventsFlushInterval,
		"media_hub.role":                       cfg.MediaHub.Role,
		"media_hub.provider":                   cfg.MediaHub.Provider,
		"media_hub.region":                     cfg.MediaHub.Region,
		"media_hub.availability_zone":          cfg.MediaHub.AvailabilityZone,
		"media_hub.public_base_url":            cfg.MediaHub.PublicBaseURL,
		"media_hub.health_url":                 cfg.MediaHub.HealthURL,
		"media_hub.max_sessions":               cfg.MediaHub.MaxSessions,
		"media_hub.max_egress_mbps":            cfg.MediaHub.MaxEgressMbps,
		"media_hub.capabilities":               cfg.MediaHub.Capabilities,
	}
}
