// Package identity provides foundation Agent identity primitives.
package identity

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

const (
	// UUIDLength is the canonical textual length of an RFC 4122 UUID.
	UUIDLength = 36

	// UUIDVersion4 is the random UUID version used by the foundation identity contract.
	UUIDVersion4 = 4

	// UUIDVariantRFC4122 identifies the UUID variant generated by NewUUID.
	UUIDVariantRFC4122 = "rfc4122"
)

// NewUUID generates a random RFC 4122 version 4 UUID.
//
// v0.1.17 intentionally provides only transient UUID generation. Persistent
// identity storage is reserved for EPIC 4.2.
func NewUUID() (string, error) {
	var bytes [16]byte
	if _, err := rand.Read(bytes[:]); err != nil {
		return "", fmt.Errorf("generate uuid entropy: %w", err)
	}

	// Version 4: high nibble of byte 6 is 0100.
	bytes[6] = (bytes[6] & 0x0f) | 0x40
	// RFC 4122 variant: high bits of byte 8 are 10.
	bytes[8] = (bytes[8] & 0x3f) | 0x80

	return formatUUID(bytes), nil
}

// NormalizeUUID trims and lowercases a UUID after validating the canonical shape.
func NormalizeUUID(value string) (string, error) {
	normalized := strings.ToLower(strings.TrimSpace(value))
	if err := ValidateUUID(normalized); err != nil {
		return "", err
	}
	return normalized, nil
}

// IsUUID reports whether value is a valid RFC 4122 version 4 UUID.
func IsUUID(value string) bool {
	return ValidateUUID(value) == nil
}

// ValidateUUID validates the canonical textual representation generated by NewUUID.
func ValidateUUID(value string) error {
	normalized := strings.ToLower(strings.TrimSpace(value))
	if normalized == "" {
		return fmt.Errorf("uuid cannot be empty")
	}
	if len(normalized) != UUIDLength {
		return fmt.Errorf("uuid must be %d characters", UUIDLength)
	}

	dashPositions := map[int]bool{8: true, 13: true, 18: true, 23: true}
	for index, char := range normalized {
		if dashPositions[index] {
			if char != '-' {
				return fmt.Errorf("uuid dash missing at position %d", index)
			}
			continue
		}
		if !isHex(char) {
			return fmt.Errorf("uuid contains non-hex character at position %d", index)
		}
	}

	if normalized[14] != '4' {
		return fmt.Errorf("uuid must be version 4")
	}
	if !strings.ContainsRune("89ab", rune(normalized[19])) {
		return fmt.Errorf("uuid must use RFC 4122 variant")
	}

	return nil
}

func formatUUID(bytes [16]byte) string {
	encoded := make([]byte, 32)
	hex.Encode(encoded, bytes[:])
	return string(encoded[0:8]) + "-" + string(encoded[8:12]) + "-" + string(encoded[12:16]) + "-" + string(encoded[16:20]) + "-" + string(encoded[20:32])
}

func isHex(char rune) bool {
	return (char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')
}
