package observability

const (
	// GrafanaName is the canonical capability name for the Grafana dashboard export.
	GrafanaName = "grafana"
)

// GrafanaDashboard describes a small dashboard JSON contract compatible with Grafana imports.
type GrafanaDashboard struct {
	Title         string         `json:"title"`
	UID           string         `json:"uid"`
	Tags          []string       `json:"tags"`
	Timezone      string         `json:"timezone"`
	SchemaVersion int            `json:"schemaVersion"`
	Version       int            `json:"version"`
	Refresh       string         `json:"refresh"`
	Panels        []GrafanaPanel `json:"panels"`
}

// GrafanaPanel is a minimal dashboard panel descriptor.
type GrafanaPanel struct {
	ID          int      `json:"id"`
	Title       string   `json:"title"`
	Type        string   `json:"type"`
	Prometheus  string   `json:"prometheus"`
	Description string   `json:"description"`
	GridPos     GridPos  `json:"gridPos"`
	Targets     []Target `json:"targets"`
}

// GridPos defines panel placement.
type GridPos struct {
	X int `json:"x"`
	Y int `json:"y"`
	W int `json:"w"`
	H int `json:"h"`
}

// Target defines a Prometheus expression.
type Target struct {
	RefID string `json:"refId"`
	Expr  string `json:"expr"`
}

// DefaultGrafanaDashboard returns the foundation dashboard export.
func DefaultGrafanaDashboard() GrafanaDashboard {
	panels := []GrafanaPanel{
		panel(1, "Agent Info", "stat", "auren_agent_info", 0, 0),
		panel(2, "Queue Length", "timeseries", "auren_queue_length", 12, 0),
		panel(3, "Download Results", "timeseries", "auren_download_total", 0, 8),
		panel(4, "Active Alerts", "stat", "auren_alerts_active", 12, 8),
		panel(5, "Trace Spans", "timeseries", "auren_traces_total", 0, 16),
		panel(6, "Central Logs", "timeseries", "auren_central_logs_total", 12, 16),
	}
	return GrafanaDashboard{Title: "Auren Transfer Agent Foundation", UID: "auren-transfer-agent-foundation", Tags: []string{"auren", "transfer-agent", "foundation"}, Timezone: "browser", SchemaVersion: 39, Version: 1, Refresh: "30s", Panels: panels}
}

func panel(id int, title string, kind string, expression string, x int, y int) GrafanaPanel {
	return GrafanaPanel{ID: id, Title: title, Type: kind, Prometheus: expression, Description: "Foundation observability panel generated by the Auren Transfer Agent.", GridPos: GridPos{X: x, Y: y, W: 12, H: 8}, Targets: []Target{{RefID: "A", Expr: expression}}}
}
